":construction: Карты :construction:":
- changed-files:
  - any-glob-to-any-file: "Resources/Maps/**/*.yml"

# "Карты-Администрация":
# - changed-files:
#   - any-glob-to-any-file: "Resources/Maps/_Forge/Admin/**/*.yml" # Grid Files

# "Карты-Ивенты":
# - changed-files:
#   - any-glob-to-any-file: "Resources/Maps/_Forge/Bluespace/**/*.yml" # Grid Files

# "Карты-Данжи":
# - changed-files:
#   - any-glob-to-any-file: "Resources/Maps/_NF/Dungeon/**/*.yml" # Grid Files

# "Карты-Аванпосты":
# - changed-files:
#   - any-glob-to-any-file:
#     - "Resources/Maps/_NF/Outpost/*.yml" # Map Files
#     - "Resources/Prototypes/_NF/Maps/Outpost/*.yml" # Prototypes Files

# "Карты-Шаттлы":
# - changed-files:
#   - any-glob-to-any-file:
#     - "Resources/Maps/_NF/Shuttles/**/*.yml" # Grid Files
#     - "Resources/Prototypes/_NF/Shipyard/**/*.yml" # Prototypes Files

# "Карты-Точки Интереса":
# - changed-files:
#   - any-glob-to-any-file:
#     - "Resources/Maps/_NF/POI/**/*.yml" # Grid Files
#     - "Resources/Prototypes/_NF/Maps/POI/**/*.yml" # Prototypes Files

":art: Спрайты :art:":
- changed-files:
  - any-glob-to-any-file:
    - "**/*.rsi/*.png"
    - "**/*.rsi/*.json"

":computer: Интерфейс :computer:":
- changed-files:
  - any-glob-to-any-file: "**/*.xaml*"

":shark: C# :shark:":
- changed-files:
  - any-glob-to-any-file: "**/*.cs"

":art: Шейдеры :art:":
- changed-files:
  - any-glob-to-any-file: '**/*.swsl'

":musical_note: Аудио :musical_note:":
- changed-files:
  - any-glob-to-any-file: '**/*.ogg'

"Без C#":
- changed-files:
  - all-globs-to-all-files: "!**/*.cs"

":book: Документация :book:":
- changed-files:
  - any-glob-to-any-file:
    - "**/*.xml"
    - "**/*.md"

":page_facing_up: Локализация :page_facing_up:":
- changed-files:
  - any-glob-to-any-file: "Resources/Locale/**/*.ftl"

":baby_chick: Прототипы :baby_chick:":
- all:
  - changed-files:
    - any-glob-to-any-file: "**/*.yml"
    - all-globs-to-any-file:
      - "!Resources/Maps/_Forge/**/*.yml"
      - "!Resources/Prototypes/Maps/_Forge/**/*.yml"

":earth_africa: Миграция Файлов :earth_africa:":
- changed-files:
  - any-glob-to-any-file: "Content.Server.Database/Migrations/**/*.cs"
