- type: latheRecipe     #Vector
  parent: BaseAmmoRecipe
  id: MagazineVector45
  result: MagazineVector45
  completetime: 5
  materials:
     Steel: 260

- type: latheRecipe     #Vector
  parent: BaseAmmoRecipe
  id: MagazineVector45Empty
  result: MagazineVector45Empty
  completetime: 5
  materials:
     Steel: 110

- type: latheRecipe     #Vector
  parent: BaseAmmoRecipe
  id: MagazineVector22
  result: MagazineVector22
  completetime: 5
  materials:
     Steel: 240

- type: latheRecipe     #Vector
  parent: BaseAmmoRecipe
  id: MagazineVector22Empty
  result: MagazineVector22Empty
  completetime: 5
  materials:
     Steel: 150

- type: latheRecipe     #ShuttleGuns
  id: ShuttleShotgunMachineCircuitboard
  result: ShuttleShotgunMachineCircuitboard
  completetime: 5
  materials:
     Steel: 1700
     Glass: 1100
     Gold: 400

- type: latheRecipe     #ShuttleGuns
  id: ShuttleGunAntiMaterialMachineCircuitboard
  result: ShuttleGunAntiMaterialMachineCircuitboard
  completetime: 13
  materials:
     Steel: 3100
     Glass: 2500
     Gold: 1600

- type: latheRecipe     #ShuttleGuns
  id: ShuttleLightRifleGunMachineCircuitboard
  result: ShuttleLightRifleGunMachineCircuitboard
  completetime: 7
  materials:
     Steel: 2400
     Glass: 1800
     Gold: 900

- type: latheRecipe     #ShuttleGuns
  id: ShuttleSMGRifleMachineCircuitboard
  result: ShuttleSMGRifleMachineCircuitboard
  completetime: 4
  materials:
     Steel: 1300
     Glass: 800
     Gold: 400

- type: latheRecipe     #ShuttleGuns
  id: ShuttleMagnumRifleMachineCircuitboard
  result: ShuttleMagnumRifleMachineCircuitboard
  completetime: 9
  materials:
     Steel: 2200
     Glass: 1700
     Gold: 1000

- type: latheRecipe     #ShuttleGuns
  parent: BaseAmmoRecipe
  id: ShuttleShotgunShellsBox
  result: ShuttleShotgunShellsBox
  completetime: 6
  materials:
     Steel: 600
     Plastic: 300

- type: latheRecipe     #ShuttleGuns
  parent: BaseAmmoRecipe
  id: ShuttleSmgRifleAmmoBox
  result: ShuttleSmgRifleAmmoBox
  completetime: 10
  materials:
     Steel: 1300
     Plastic: 300

- type: latheRecipe     #ShuttleGuns
  parent: BaseAmmoRecipe
  id: ShuttleRifleAmmoBox
  result: ShuttleRifleAmmoBox
  completetime: 15
  materials:
     Steel: 2700
     Plastic: 300

- type: latheRecipe     #ShuttleGuns
  parent: BaseAmmoRecipe
  id: ShuttleMagnumRifleAmmoBox
  result: ShuttleMagnumRifleAmmoBox
  completetime: 8
  materials:
     Steel: 900
     Plastic: 300
